version: "3.9"

services:

  nginx-dev:
    image: nginx:1.21.6
    container_name: nginx
    restart: unless-stopped
    networks:
      - uinvest
    profiles:
      - "dev"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static-files:/srv/nginx/static-files:ro

networks:
  uinvest:
    name: uinvest
