version: "3.9"

services:

  nginx:
    image: nginx:1.21.6
    container_name: nginx
    restart: unless-stopped
    networks:
      - uinvest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - order-api
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static-files:/srv/nginx/static-files:ro

  db:
    image: mariadb:10.7.3
    container_name: db
    restart: unless-stopped
    env_file: ./db/.env
    volumes:
      # no mount point for base so doesn't get saved for tests
      # all files in `/docker-entrypoint-initdb.d` will be executed on start
      # BUT ONLY IF /var/lib/mysql doesn't exist
      - "./db/schemas:/docker-entrypoint-initdb.d/"
    networks:
      - uinvest

  order-api:
    image: orderapi
    container_name: orderapi
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./order-api/Dockerfile
    restart: unless-stopped
    env_file: ./order-api/.env
    networks:
      - uinvest

networks:
  uinvest:
    name: uinvest
